id: intro_dynamicon_smith
learningObjectives:
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "Hey ${user.firstName}!"
            delay: 300
          - text: "So, we've got a new feature we want to implement on our website. We want to automatically create a unique image for each new user based on their information"
            delay: 4500
          - text: "Now, I know you're probably thinking \"But Lucca, I'm not a designer!\" Don't worry, we'll be using code to generate these images."
            delay: 4000
          - text: "Are you ready to dive into the complexities, let me know when you're ready."
            delay: 2000

trigger:
  type: user_message
  params:
    person: lucca
  flowNode:
    if:
      conditions:
        - conditionId: is_user_message_text_ready_to_continue
      then:
        do:
          - actionId: finish_step
      else:
        do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
                - text: "let me know when you're ready. By typing ready | done"
                  delay: 200
