id: create_utility_function_dynamicon_smith
learningObjectives:
  - Creating and using utility functions
  - use of Javascript's canvas API, and converting canvas into data URL
hints:
  - Try to find what all the users that drop in the funnel have in common
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "First things first, let's create a utility function that takes in the user's information and generates a dataURL of the image."
            delay: 2500
          - text: "To create an image, we use HTML canvas. You can read more about (canvas here)[https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API]."
            delay: 2000

trigger:
  type: user_message
  params:
    person: keen
  flowNode:
    if:
      conditions:
        - conditionId: text_match_regex
          params:
            text: "${userMessageText}"
            regex: mobile|android|ios|iphobe|non web
            flags: i
      then:
        do:
          - actionId: bot_message
            params:
              person: keen
              messages:
                - text: Good catch! I'll let the support team know.
                  delay: 1300
          - actionId: finish_step
      else:
        do:
          - actionId: bot_message
            params:
              person: keen
              messages:
                - text: Try again! I'm sure you'll figure this out.
                  delay: 2500
