id: create_utils_dir_dynamicon_smith
learningObjectives:
  - Learn about HTML canvas, manipulate canvas using javascript
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "First things first, let's create a utility function that takes in the user's information and generates a dataURL of the image."
            delay: 2500
          - text: "To create an image, we use canvas. You can read more about [canvas here](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API)."
            delay: 2000
          - text: "When you're ready let me know."
            delay: 700

trigger:
  type: user_message
  params:
    person: lucca
  flowNode:
    if:
      conditions:
        - conditionId: is_user_message_text_ready_to_continue
      then:
        do:
          - actionId: finish_step
      else:
        do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
                - text: "I don't understand what you are saying."
                  delay: 400

