id: send_url_with_post_request_dynamicon_smith
learningObjectives:
  - send payload to backend using HTTP post request.
hints:
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages: 
          - text: "Next, we'll call this utility function that you build earliar when a new user signs up on the website."
            delay: 2600
          - text: "When the user submits the form, take this information and call our getUserAvatar method to get the image URL."
            delay: 2500
          - text: "Now, add this image in post request payload"
            delay: 1100
          - text: "Are you ready?"
            delay: 100
trigger:
  type: user_message
  params:
    person: lucca
  flowNode:
    if:
      conditions:
        - conditionId: is_user_message_text_ready_to_continue
      then:
        do:
          - actionId: finish_step
      else:
        do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
                - text: "I don't understand what you are saying."
                  delay: 400
