id: create_utility_function_dynamicon_smith
learningObjectives:
  - Creating and using utility functions
  - use of Javascript's canvas API, and converting canvas into data URL
hints:
  - Try to find what all the users that drop in the funnel have in common
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "First things first, let's create a utility function that takes in the user's information and generates a dataURL of the image."
            delay: 2500
          - text: "To create an image, we use HTML canvas. You can read more about [canvas here](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API)."
            delay: 2000
          - text: "When you're ready let me know."
            delay: 700

trigger:
  type: user_message
  params:
    person: lucca
  flowNode:
    if:
      conditions:
        - conditionId: is_user_message_text_ready_to_continue
      then:
        do:
          - actionId: bot_message
            params:
              person: keen
              messages:
                - text: "Make a utils directory inside frontend/src/, and then make a file that exports required functions inside the utils directory so that it can be imported and used. Make sure the name of the file is getUserAvatar.js."
                  delay: 2500
                - text: "Make sure the name of the file is getUserAvatar.js."
                  delay: 800
                - text: "Remember that the function should return base64 data URL. When you're done with that, open a PR."
                  delay: 2500
          - actionId: finish_step
      else:
        do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
                - text: "I don't understand what you are saying."
                  delay: 400
